---
- name: Setup Tomcat, MySQL, Java, and Maven
  hosts: prod
  become: true
  tasks:

    # Install Tomcat
    - name: Download Tomcat 8
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.88/bin/apache-tomcat-8.5.88.tar.gz
        dest: /opt/
    
    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-8.5.88.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Copy tomcat-users.xml  
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /opt/apache-tomcat-8.5.88/conf/tomcat-users.xml

    - name: Copy manager.xml
      copy:
        src: /home/ubuntu/manager.xml
        dest: /opt/apache-tomcat-8.5.88/conf/Catalina/localhost/manager.xml

    - name: Make Tomcat executable
      file:
        path: /opt/apache-tomcat-8.5.88/bin/catalina.sh
        mode: '0755'

    - name: Start Tomcat
      shell: nohup /opt/apache-tomcat-8.5.88/bin/startup.sh &

    # Install MySQL
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: latest
        update_cache: yes
    
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    # Install Java
    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: latest
        update_cache: yes

    # Install Maven
    - name: Install Maven
      apt:
        name: maven
        state: latest
        update_cache: yes
